/* Hero Homes — Floor apartment hold request */
(() => {
  'use strict';
  const SUPABASE_URL='https://lgsuzidpqnqgyqucrotx.supabase.co';
  const SUPABASE_KEY='sb_publishable_K587kfedNvRzY0t03KfAzQ_zVMjCcuS';
  const MAP={'Tower-9.html':'9','Tower-10.html':'10','Tower-11.html':'11','Tower-12.html':'12','Tower-C-12-A.html':'12A'};
  const file=location.pathname.split('/').pop();
  const tower=MAP[file]||sessionStorage.getItem('selectedTower')||'';
  const p=new URLSearchParams(location.search);
  const floor=Number(p.get('floor')||sessionStorage.getItem('selectedFloor')||sessionStorage.getItem('heroHomesFloor')||1);
  const saved=()=>{try{return JSON.parse(localStorage.getItem('heroHomesVisitor')||'null')}catch(_){return null}};
  const headers=()=>({'Content-Type':'application/json','apikey':SUPABASE_KEY,'Authorization':`Bearer ${SUPABASE_KEY}`,'Prefer':'return=minimal'});
  async function insert(table,payload){const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}`,{method:'POST',headers:headers(),body:JSON.stringify(payload)});if(!r.ok){let m=`Supabase ${r.status}`;try{const x=await r.json();m=x.message||x.details||m}catch(_){}throw new Error(m)}return r.json()}
  function create(){
    if(document.getElementById('hhHoldModal'))return;
    const s=document.createElement('style');s.textContent=`#hhHoldModal{position:fixed;inset:0;z-index:2147483000;display:none;align-items:center;justify-content:center;background:rgba(0,0,0,.65);backdrop-filter:blur(8px);padding:20px;font-family:Arial,sans-serif}#hhHoldModal.open{display:flex}#hhHoldModal .hh-card{width:min(520px,100%);max-height:90vh;overflow:auto;background:#111820;color:#fff;border:1px solid #33404d;border-radius:20px;padding:24px}#hhHoldModal .hh-head{display:flex;justify-content:space-between;align-items:center}#hhHoldModal .hh-close{border:0;background:#26303b;color:#fff;border-radius:10px;width:38px;height:38px;font-size:20px;cursor:pointer}#hhHoldModal .hh-detail{background:#19232d;border:1px solid #33404d;border-radius:14px;padding:15px;margin:16px 0}#hhHoldModal form{display:grid;gap:12px}#hhHoldModal input{width:100%;box-sizing:border-box;padding:13px;border-radius:10px;border:1px solid #344454;background:#0c1218;color:#fff}#hhHoldModal button[type=submit]{padding:14px;border:0;border-radius:11px;background:#f3b900;color:#111;font-weight:700;cursor:pointer}#hhHoldModal .saved{background:#19232d;border:1px solid #33404d;padding:12px;border-radius:12px;font-size:13px}`;document.head.appendChild(s);
    const m=document.createElement('div');m.id='hhHoldModal';m.innerHTML=`<div class="hh-card"><div class="hh-head"><h2>Request to Hold</h2><button type="button" class="hh-close" id="hhHoldClose">×</button></div><div class="hh-detail"><strong>Want to request this apartment?</strong><div id="hhApartmentDetail"></div></div><div id="hhSaved" class="saved" style="display:none"></div><form id="hhHoldForm"><input name="firstName" placeholder="First Name" required><input name="lastName" placeholder="Last Name"><input name="phone" placeholder="Phone Number" inputmode="numeric" maxlength="10" required><input name="email" type="email" placeholder="Email Address" required><input name="city" placeholder="City" required><button type="submit">Request to Hold</button></form><div id="hhSuccess" style="display:none;text-align:center;padding:20px">✓ Hold request submitted successfully.</div></div>`;document.body.appendChild(m);
    document.getElementById('hhHoldClose').onclick=close;m.addEventListener('click',e=>{if(e.target===m)close()});document.getElementById('hhHoldForm').addEventListener('submit',submit);
  }
  let selectedUnit=null;
  function open(unit){create();selectedUnit=Number(unit);sessionStorage.setItem('selectedUnit',String(selectedUnit));document.getElementById('hhApartmentDetail').textContent=`Tower ${tower} • Floor ${String(floor).padStart(2,'0')} • Unit ${selectedUnit}`;const f=document.getElementById('hhHoldForm'), sv=saved(), savedBox=document.getElementById('hhSaved');document.getElementById('hhSuccess').style.display='none';f.style.display='grid';f.reset();if(sv){const parts=(sv.fullName||'').split(/\s+/);f.firstName.value=parts.shift()||'';f.lastName.value=parts.join(' ');f.phone.value=sv.mobile||'';f.email.value=sv.email||'';f.city.value=sv.city||'';[...f.querySelectorAll('input')].forEach(x=>x.style.display='none');savedBox.style.display='block';savedBox.innerHTML=`Using saved details<br><strong>${sv.fullName||''}</strong> • ${sv.mobile||''}<br>${sv.email||''} • ${sv.city||''}`}else{[...f.querySelectorAll('input')].forEach(x=>x.style.display='');savedBox.style.display='none'}document.getElementById('hhHoldModal').classList.add('open');document.body.style.overflow='hidden'}
  function close(){const m=document.getElementById('hhHoldModal');if(m)m.classList.remove('open');document.body.style.overflow=''}
  async function submit(e){e.preventDefault();if(!selectedUnit)return;const f=e.currentTarget,sv=saved();const first=f.firstName.value.trim(),last=f.lastName.value.trim(),phone=f.phone.value.trim(),email=f.email.value.trim(),city=f.city.value.trim();if(!/^\d{10}$/.test(phone))return alert('Please enter a valid 10-digit phone number.');const name=`${first} ${last}`.trim(),detail=`Tower ${tower} • Floor ${String(floor).padStart(2,'0')} • Unit ${selectedUnit}`,btn=f.querySelector('button[type=submit]');btn.disabled=true;btn.textContent='Submitting...';try{if(!sv){await insert('visitors',{name,first_name:first,last_name:last,mobile:phone,phone,dial_code:'+91',email,city,tower,floor,unit:selectedUnit,source_page:location.href});localStorage.setItem('heroHomesVisitor',JSON.stringify({fullName:name,mobile:phone,email,city,tower,floor,unit:selectedUnit,submittedAt:new Date().toISOString()}))}await insert('hold_requests',{tower,floor,unit:selectedUnit,apartment_detail:detail,unit_number:`${tower}-${floor}-${selectedUnit}`,property_name:'Hero Homes',source_type:'hero_homes',plot_number:null,floor_number:String(floor),visitor_name:sv?.fullName||name,visitor_mobile:sv?.mobile||phone,visitor_email:sv?.email||email,visitor_city:sv?.city||city,status:'pending'});f.style.display='none';document.getElementById('hhSaved').style.display='none';document.getElementById('hhSuccess').style.display='block'}catch(err){console.error('Hero Homes hold request:',err);alert(`Could not submit request: ${err.message}`)}finally{btn.disabled=false;btn.textContent='Request to Hold'}}
  function wire(){create();[1,2].forEach(unit=>{const path=document.getElementById(`Appartment_x5F_${unit}`);if(path&&!path.dataset.hhWired){path.dataset.hhWired='1';path.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();open(unit)},true)}})}
  document.addEventListener('DOMContentLoaded',()=>{if(floor>=1&&floor<=32){sessionStorage.setItem('selectedFloor',String(floor));sessionStorage.setItem('heroHomesFloor',String(floor));sessionStorage.setItem('selectedTower',tower);sessionStorage.setItem('heroHomesTower',tower)}wire()});
})();
